### ISSUE TITLE
Upkeep for readr

### ISSUE THREAD

**Issue by jennybc** [tidyverse/readr#1372]
Pre-history

* [x] `usethis::use_readme_rmd()`
* [x] `usethis::use_roxygen_md()`
* [x] `usethis::use_github_links()`
* [ ] ~~`usethis::use_pkgdown_github_pages()`~~
* [x] `usethis::use_tidy_github_labels()`
* [x] `usethis::use_tidy_style()`
* [x] `usethis::use_tidy_description()`
* [x] `urlchecker::url_check()`

2020

* [x] `usethis::use_package_doc()`
Consider letting usethis manage your `@importFrom` directives here.
`usethis::use_import_from()` is handy for this.
* [x] `usethis::use_testthat(3)` and upgrade to 3e, [testthat 3e vignette](https://testthat.r-lib.org/articles/third-edition.html)
* [x] Align the names of `R/` files and `test/` files for workflow happiness.
`usethis::rename_files()` can be helpful.

2021

* [ ] ~~`usethis::use_tidy_dependencies()`~~
* [x] `usethis::use_tidy_github_actions()` and update artisanal actions to use `setup-r-dependencies`
* [x] Remove check environments section from `cran-comments.md`
* [x] Bump required R version in DESCRIPTION to 3.4
* [x] Use lifecycle instead of artisanal deprecation messages, as described in [Communicate lifecycle changes in your functions](https://lifecycle.r-lib.org/articles/communicate.html)

2022

* [x] `usethis::use_tidy_coc()`
* [ ] ~~Update pkgdown site using instructions at <https://tidytemplate.tidyverse.org>~~
* [ ] ~~Re-publish released site using [r-lib/pkgdown#2051](https://github.com/r-lib/pkgdown/pull/2051)~~
* [x] Ensure pkgdown `development` is `mode: auto` in pkgdown config
* [x] Handle and close any still-open `master` --> `main` issues
* [x] Update README badges, instructions in [r-lib/usethis#1594](https://github.com/r-lib/usethis/issues/1594)
* [ ] ~~Update errors to rlang 1.0.0~~ _opened a separate issue_ #1384

**Comment by sbearrows** [comment]
Reposting so I can add checkmarks

* [ ] usethis::use_tidy_coc()
* [ ] Update errors to rlang 1.0.0
* [ ] Update pkgdown site using instructions at https://tidytemplate.tidyverse.org/
* [ ] Re-publish released site using https://github.com/r-lib/pkgdown/pull/2051
* [ ] Ensure pkgdown development is mode: auto in pkgdown config
* [ ] Handle and close any still-open master --> main issues
* [ ] Update README badges, instructions in https://github.com/r-lib/usethis/issues/1594

**Comment by jennybc** [comment]
Before we close this @sbearrows, let's follow up on items that are struck through.

`usethis::use_tidy_dependencies()`: We aren't implementing this now, in the absence of specific plans to take advantage of it. But let's note what would change in readr, because it means we should have a low threshold for making these changes in the future:

* Add glue to Imports. If using glue would be handy, we should just do it.
* Move withr from Suggests to Imports. If wider internal use of withr would be handy, do it.
* Import rlang's namespace.
* Add the purrr compatibility file.

pkgdown: Nothing needs to be done for readr because it's already been modernized and re-published. readr was one of the "guinea pig" packages where our update procedure was worked out.

Update errors to rlang 1.0.0: I don't understand why this is struck through. Or, rather, it feels like we should open a new separate issue about using rlang for conditions in readr.

@sbearrows Will you confirm / comment on the above?

**Comment by sbearrows** [comment]
Yes, I still need to open a new issue for the item "Update errors to rlang 1.0.0" which I will link to here.

Otherwise, I think everything else you've mentioned covers items that are struck through.

Thanks for helping me document these last few items!

**Comment by jennybc** [comment]
Ok I think we are done!
